openapi: 3.0.0
info:
  title: Payment Transaction API
  description: API for managing payment transactions
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /transactions:
    post:
      summary: Create a new transaction
      operationId: createTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentTransactionRequest'
      responses:
        '201':
          description: Transaction created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentTransactionResponse'

    get:
      summary: Retrieve a list of all transactions
      operationId: getAllTransactions
      responses:
        '200':
          description: List of transactions retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentTransactionResponse'

  /transactions/{id}:
    get:
      summary: Retrieve details of a single transaction
      operationId: getTransactionById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Transaction details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentTransactionResponse'
        '404':
          description: Transaction not found

    put:
      summary: Update a transaction (e.g., change status)
      operationId: updateTransaction
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentTransactionRequest'
      responses:
        '200':
          description: Transaction updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentTransactionResponse'
        '404':
          description: Transaction not found

    delete:
      summary: Delete a transaction
      operationId: deleteTransaction
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Transaction deleted successfully
        '404':
          description: Transaction not found

components:
  schemas:
    PaymentTransactionRequest:
      type: object
      properties:
        amount:
          type: number
          format: double
          example: 100.50
        currency:
          type: string
          example: USD
        status:
          type: string
          enum:
            - PENDING
            - COMPLETED
            - EXPIRED
          example: PENDING
      required:
        - amount
        - currency
        - status

    PaymentTransactionResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        amount:
          type: number
          format: double
          example: 100.50
        currency:
          type: string
          example: USD
        status:
          type: string
          enum:
            - PENDING
            - COMPLETED
            - EXPIRED
          example: PENDING
        createdAt:
          type: string
          format: date-time
          example: "2023-10-01T12:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2023-10-01T12:00:00Z"